src/app/mod_question/__init__.py
#from flask import Blueprint

#mod_question = Blueprint('mod_question', __name__)

#from . import views

src/app/mod_question/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import QuestionForm
from datetime import datetime
from sqlalchemy import and_
from .models import Question
from app.mod_user.models import User
from app.mod_answer.models import Answer
from app.mod_tag.models import Tag
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
mod_question = Blueprint('mod_question', __name__)

@mod_question.route('/question/<question_id>', methods = ['GET', 'POST'])
def showQuestion(question_id):
	"""This function shows a particular question by given question id"""
	question = Question.query.filter_by(question_id = question_id).all()
	if not question:
		return redirect(url_for('index'))
	answers = Answer.query.filter_by(question_id = question_id).all()
	answers = question[0].answers
	comments = Comment.query.filter_by(question_id = question_id).all()
	enabled = True
	if g.user.is_authenticated and len(Answer.query.filter_by(question_id = question_id, user_id = g.user.user_id).all()):
		enabled = False
	return render_template('mod_question/showQuestion.html', title = question[0].title, questions = question, answers = answers, enabled = enabled, comments = comments)

@mod_question.route('/addQuestion', methods = ['GET', 'POST'])
@login_required
def addQuestion():
	"""This function adds question which the user has written through form"""
	form = QuestionForm()
	print(form.validate_on_submit())
	if form.validate_on_submit():
		print(form.tag.data)
		code = "\n" + form.code.data
		question = Question(title = form.title.data, body = form.body.data, code = code, author = g.user, timestamp = datetime.utcnow(), answered = 0)
		db.session.add(question)
		db.session.commit()
		tags = form.tag.data.split(",")
		print(tags)
		for i in tags:
			tag = Tag(body = i, question = question)
			db.session.add(tag)
			db.session.commit()
		return redirect(url_for('mod_home.index'))
	return render_template('mod_question/addQuestion.html', title = 'Add Question', form = form)

@mod_question.route('/unansweredQuestions')
@mod_question.route('/unansweredQuestions/<int:page>', methods=['GET', 'POST'])
def unansweredQuestions(page=1):
	"""Returns number of unanswered questions"""
	questions = Question.query.filter(Question.answered == 0).order_by(Question.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
	#questions = Question.query.filter(Question.answered == 0).order_by(Question.timestamp.desc()).paginate(page, POSTS_PER_PAGE, False)
	return render_template('mod_question/unansweredQuestions.html', title = 'Unanswered Questions', questions = questions)

@mod_question.route('/answeredQuestions')
@mod_question.route('/answeredQuestions/<int:page>', methods=['GET', 'POST'])
def answeredQuestions(page=1):
	"""Returns number of answered questions"""
	questions = Question.query.filter(Question.answered != 0).order_by(Question.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
	#questions = Question.query.filter(Question.answered != 0).order_by(Question.timestamp.desc()).paginate(page, POSTS_PER_PAGE, False)
	return render_template('mod_question/answeredQuestions.html', title = 'Answered Questions', questions = questions)

"""Registers a function to run before each request.The function will be called without any arguments. 
If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	def user(user_id):
		"""filters users by user_id and returns an object of users"""
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

@app.context_processor
def vote_check():
	"""tells number of votes based on whether it is upvote,downvote on question or answer"""
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/mod_tag/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import LoginForm, RegistrationForm, QuestionForm, AnswerForm, TagForm
from app.mod_user.models import User
from app.mod_question.models import Question
from app.mod_answer.models import Answer
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
from app.mod_tag.models import Tag
from datetime import datetime
from sqlalchemy import and_
#from . import mod_tag
mod_tag = Blueprint('mod_tag', __name__)

@mod_tag.route('/searchByTags', methods = ['GET', 'POST'])
def searchByTags():
	"""search question by tags in question database"""
	form = TagForm()
	if form.validate_on_submit():
		tag_data = form.tag.data
		print (tag_data.split(','))
		tags = []
		for tag_body in tag_data.split(','):
			for tag in Tag.query.filter_by(body = tag_body).all():
				tags.append(tag)
		#tags = Tag.query.filter(Tag.body.in_(tag_data)).all()
		questions = []
		for tag in tags:
			question = Question.query.filter_by(question_id = tag.question_id).first()
			if question not in questions:
				questions.append(question)
		return render_template('mod_tag/searchByTags.html', form = form, questions = questions, title = 'Search By Tags')
	return render_template('mod_tag/searchByTags.html',form = form, questions = [], title = 'Search By Tags')

"""@mod_tag.route('/searchByTags', methods = ['GET', 'POST'])
def searchByTags():
	#search question by tags in question database
	form = TagForm()
	if form.validate_on_submit():
		tag_data = form.tag.data
		tags = Tag.query.filter(Tag.body.in_(tag_data)).all()
		questions = []
		for tag in tags:
			question = Question.query.filter_by(question_id = tag.question_id).first()
			if question not in questions:
				questions.append(question)
		return render_template('mod_tag/searchByTags.html', form = form, questions = questions, title = 'Search By Tags')
	return render_template('mod_tag/searchByTags.html',form = form, questions = [], title = 'Search By Tags')"""


"""Registers a function to run before each request.The function will be called without any arguments. 
   If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	def user(user_id):
		"""filters users by user_id and returns an object of users"""
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

"""tells number of votes based on whether it is upvote,downvote on question or answer"""
@app.context_processor
def vote_check():
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/mod_user/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import ProfileForm
from .models import User
from app.mod_answer.models import Answer
from app.mod_question.models import Question
from app.mod_tag.models import Tag
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
from datetime import datetime
from sqlalchemy import and_
#from . import mod_user
mod_user = Blueprint('mod_user', __name__)

@mod_user.route('/user', methods=['GET', 'POST'])
def profile():
	form = ProfileForm()
	if form.validate_on_submit():
		username = form.username.data
		user = User.query.filter_by(username = username).first()
		if user == None:
			flash ('User %s not found' % username)
			return redirect(url_for('mod_user.profile'))
		questions = user.questions.order_by(Question.timestamp.desc())
		return render_template('mod_user/profile.html', title = 'Profile', form = form, questions = questions, user = user)
	else:
		return render_template('mod_user/searchuser.html', title = 'Search User', form = form)

@mod_user.route('/myAnswers')
@mod_user.route('/myAnswers/<int:page>', methods=['GET', 'POST'])
@login_required
def myAnswers(page=1):
	"""This function shows the answers of a particular user"""
	user = User.query.filter_by(user_id = g.user.user_id).first()
	answers = user.answers
	questions = []
	for answer in answers:
		questions.append(answer.question)
	return render_template('mod_user/myAnswers.html', title = 'My Answers', questions = questions)

@mod_user.route('/dashboard')
@mod_user.route('/dashboard/<int:page>', methods=['GET', 'POST'])
@login_required
def dashboard(page=1):
	user = User.query.filter_by(user_id = g.user.user_id).first()
	questions = user.questions.order_by(Question.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
	return render_template('mod_user/dashboard.html', title = 'My Questions', questions = questions)

"""Registers a function to run before each request.The function will be called without any arguments. 
If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	def user(user_id):
		"""filters users by user_id and returns an object of users"""
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

@app.context_processor
def vote_check():
	"""tells number of votes based on whether it is upvote,downvote on question or answer"""
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/templates/mod_question/addQuestion.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %} Add Question {% endblock %}
{% block body %}
<div class="container">
	<div class="container">
		<img src="{{ current_user.avatar(120) }}" style="display: block; margin: auto;">
		<br>
		<p style="text-align: center;"><span class="text-warning"> Welcome {{ current_user.username }} </span></p>
		<p style="text-align: center;"><i> Last seen on: {{ current_user.last_seen }}</i></p>
	</div>
	<br>
	<div class="col-md-12 text-center">
    	<ul class="nav nav-pills">
      		<li><a href="{{ url_for('mod_user.dashboard') }}">My Questions</a></li>
  			<li><a href="{{ url_for('mod_user.myAnswers') }}">My Answers</a></li>
  			<li class="active"><a href="{{ url_for('mod_question.addQuestion') }}">Ask A Question</a></li>
    	</ul>
	</div>
	<br>
	<br>
	<br>
	<div class="content-section">
  		<div class="center">
    	<h1>Post Question</h1>
    	<br>
    		<form class = "form" method="post" action="" role = "form">
    		{{ form.csrf_token }}
    		{{ wtf.form_field(form.title) }}
    		{{ wtf.form_field(form.body) }}
    		{{ wtf.form_field(form.code) }}
    		{{ wtf.form_field(form.tag, data_role="tagsinput") }}
    		{{ wtf.form_field(form.submit) }}
    		<!--<button type="submit">Submit</button>-->
    		</form>
  		</div>
	</div>
</div>
{% endblock %}

src/app/templates/mod_question/answeredQuestions.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block body %}
<div class="container">
    <div class="col-md-12 text-center">
        <ul class="nav nav-pills">
            <li><a href="{{ url_for('mod_home.index') }}">All</a></li>
            <li><a href="{{ url_for('mod_question.unansweredQuestions') }}">Unanswered</a></li>
            <li class="active"><a href="{{ url_for('mod_question.answeredQuestions') }}">Answered</a></li>
            <li><a href="{{ url_for('mod_tag.searchByTags') }}">Search By Tags</a></li>
            <li><a href="{{ url_for('mod_user.profile') }}">Search User</a></li>
        </ul>
    </div>
    <br>
    <div class="col-md-12 text-center">
        {% for question in questions.items %}
            {% include 'mod_question/questionLink.html' %}
        {% endfor %}
    </div>
    <ul class="pager">
    {% if questions.has_prev %}<li><a href="{{ url_for('mod_question.answeredQuestions', page=questions.prev_num) }}">Previous</a></li>{% else %}<li>Previous</li>{% endif %}  
    {% if questions.has_next %}<li><a href="{{ url_for('mod_question.answeredQuestions', page=questions.next_num) }}">Next</a></li>{% else %}<li>Next</li>{% endif %}
    </ul>  
</div>
{% endblock %}

src/app/templates/mod_question/question.html
<h2 style="text-align: left;"><a href="#">{{ question.title }}</a></h2>
<hr>
<div class="well well-lg">
	{{ question.body }}
</div>
<pre class="prettyprint" style="text-align: justify;">
	{{ question.code }}
</pre>
<table class="table table-condensed" style="padding: 0px; margin-right: 0px;">
	<tr>
		<td>
		{% if current_user.is_authenticated and vote_allowed_check(question.question_id, 1, 1) %}
			<!--<a href = "{{ url_for('mod_vote.questionUpvote', question_id = question.question_id) }}" class="btn btn-success btn-block btn-default">Upvotes: 
				<span style="font-weight: bold;">{{ question.upvotes.all()|length }}</span>
			</a>-->
			<a id="question-upvote-{{ question.question_id }}" class="btn btn-success btn-block btn-default" onclick="questionUpvote(this)">Upvotes: 
				<span style="font-weight: bold;">{{ question.upvotes.all()|length }}</span>
			</a>
		{% else %}
			<a href = "{{ url_for('mod_vote.questionUpvote', question_id = question.question_id) }}" onclick="return false;" style="cursor: default;" class="btn btn-success btn-block btn-default">Upvotes: 
				<span style="font-weight: bold;">{{ question.upvotes.all()|length }}
				</span>
			</a>
		{% endif %}
		</td>
		<td>
		{% if current_user.is_authenticated and vote_allowed_check(question.question_id, 2, 1) %}
			<!--<a href = "{{ url_for('mod_vote.questionDownvote', question_id = question.question_id) }}"  class="btn btn-success btn-block btn-default">Downvotes: 
				<span style="font-weight: bold;">{{ question.downvotes.all()|length }}
				</span>
			</a>-->
			<a id="question-downvote-{{ question.question_id }}" class="btn btn-success btn-block btn-default" onclick="questionDownvote(this)">Downvotes: 
				<span style="font-weight: bold;">{{ question.downvotes.all()|length }}</span>
			</a>
		{% else %}
			<a href = "{{ url_for('mod_vote.questionDownvote', question_id = question.question_id) }}" onclick="return false;" style="cursor: default;" class="btn btn-success btn-block btn-default">Downvotes: 
				<span style="font-weight: bold;">{{ question.downvotes.all()|length }}
				</span>
			</a>
		{% endif %}
		</td>
		<td>
			<img src="{{ question.author.avatar(40) }}" style="float: left; padding-right: 5px;">
			<p class="text-warning" style="padding-left: 10px; font-size: 14px; font-weight: bold;">
				{{ question.author.username }}<br>{{ question.timestamp }}
			</p>
		</td>
	</tr>
</table>
<p style="text-align: left;">
	{% for tag in question.tags %}
		<span class="label label-info" style="font-size: 14px;">{{ tag.body }}</span>
	{% endfor %}
</p>
<div class="container">
	<h3 style="text-align: left;">Comments: </h3>
	<hr>
</div>
<div class="comments-container">
	<ul id="comments-list" class="comments-list">
	{% for comment in comments %}
		{% include 'mod_comment/comments.html' %}
	{% endfor %}
	{% if current_user.is_authenticated %}
		<li>
			<div class="comment-main-level" id = "add-question-comment" data-user-id = "{{ current_user.user_id }}" data-question-id = "{{ question.question_id }}">
			<div class="comment-avatar"><img src="{{ current_user.avatar(120) }}" alt=""></div>
				<div class="comment-box">
					<div class="comment-head">
						<h6 class="comment-name by-author"><span class="comment-author">{{ current_user.username }}</a></h6>
					</div>
				<div class="comment-content" style="text-align: justify;">
					<div class="form-group">
						<textarea class="form-control" rows="3" id = "comment-body" name = "comment-body"></textarea><br>
						<button type="submit" class="btn btn-primary" onclick="addQuestionComment()">Add Comment</button><br>
					</div>
				</div>
				</div>
			</div>
		</li>
	</ul>
	{% endif %}
</div>
<hr>
<!--http://i9.photobucket.com/albums/a88/creaticode/avatar_1_zps8e1c80cd.jpg-->

src/app/templates/mod_question/questionLink.html
<h3 style="text-align: left;"><a href="{{ url_for('mod_question.showQuestion', question_id = question.question_id) }}">{{ question.title }}</a></h3>
<hr>
<div class="well well-lg">
	{% if question.body.split()|length > 25 %}
		{{ " ".join((question.body.split())[:25]) }}
	{% else %}
		{{ question.body }}
	{% endif %}
</div>
<hr>

src/app/templates/mod_question/showQuestion.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block body %}
<div class="container">
    <div class="col-md-12 text-center">
        <ul class="nav nav-pills">
            <li><a href="{{ url_for('mod_home.index') }}">All</a></li>
            <li><a href="{{ url_for('mod_question.unansweredQuestions') }}">Unanswered</a></li>
            <li><a href="{{ url_for('mod_question.answeredQuestions') }}">Answered</a></li>
            <li><a href="{{ url_for('mod_tag.searchByTags') }}">Search By Tags</a></li>
            <li><a href="{{ url_for('mod_user.profile') }}">Search User</a></li>
        </ul>
    </div>
    <br>
    <div class="col-md-12 text-center">
        {% for question in questions %}
            {% include 'mod_question/question.html' %}
        {% endfor %}
    </div>
    <div class="container">
        <h3>Answers: </h3>
        <hr>
    </div>
    <div class="col-md-12 text-center">
        {% for answer in answers %}
            {% include 'mod_answer/answer.html' %}
        {% endfor %}
    </div>
    {% if current_user.is_authenticated and enabled %}
        <div class="container" style="text-align: center;">
            <a href="{{ url_for('mod_answer.answerQuestion', question_id = questions[0].question_id) }}" class="btn btn-success btn-lg">Submit Answer</a>
        </div>
    {% endif %}
    <br>
</div>
{% endblock %}

src/app/templates/mod_question/unansweredQuestions.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block body %}
<div class="container">
    <div class="col-md-12 text-center">
        <ul class="nav nav-pills">
            <li><a href="{{ url_for('mod_home.index') }}">All</a></li>
            <li class="active"><a href="{{ url_for('mod_question.unansweredQuestions') }}">Unanswered</a></li>
            <li><a href="{{ url_for('mod_question.answeredQuestions') }}">Answered</a></li>
            <li><a href="{{ url_for('mod_tag.searchByTags') }}">Search By Tags</a></li>
            <li><a href="{{ url_for('mod_user.profile') }}">Search User</a></li>
        </ul>
    </div>
    <br>
    <div class="col-md-12 text-center">
        {% for question in questions.items %}
            {% include 'mod_question/questionLink.html' %}
        {% endfor %}
    </div>
    <ul class="pager">
    {% if questions.has_prev %}<li><a href="{{ url_for('mod_question.unansweredQuestions', page=questions.prev_num) }}">Previous</a></li>{% else %}<li>Previous</li>{% endif %}  
    {% if questions.has_next %}<li><a href="{{ url_for('mod_question.unansweredQuestions', page=questions.next_num) }}">Next</a></li>{% else %}<li>Next</li>{% endif %}
    </ul>    
</div>
{% endblock %}