src/app/mod_user/models.py
from app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from hashlib import md5

"""This is the model for User class"""
class User(UserMixin, db.Model):
	__tablename__ = "users"
	user_id = db.Column(db.Integer, primary_key = True, autoincrement = True)
	username = db.Column(db.String, index = True, unique = True)
	email = db.Column(db.String, index = True, unique = True)
	password_hash = db.Column(db.String(128))
	last_seen = db.Column(db.DateTime)
	questions = db.relationship('Question', backref = 'author', lazy = 'dynamic')
	answers = db.relationship('Answer', backref = 'author', lazy = 'dynamic')
	comments = db.relationship('Comment', backref = 'author', lazy = 'dynamic')
	upvotes = db.relationship('Upvote', backref = 'author', lazy = 'dynamic')
	downvotes = db.relationship('Downvote', backref = 'author', lazy = 'dynamic')

	@property
	def password(self):
		raise AttributeError('password is not a readable attribute')

	"""This generates password based on hashing """
	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)
	"""This verifies password based on hashing"""
	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	def get_id(self):
		return str(self.user_id)

	"""Uses gravatar API"""
	def avatar(self, size):
		return 'http://www.gravatar.com/avatar/%s?d=identicon&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
	def __repr__(self):
		return '<User %r>' % (self.username)

"""Refer to Flask/login documentation"""
@login_manager.user_loader
def user_loader(user_id):
	return User.query.get(int(user_id))

src/app/mod_home/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import LoginForm, RegistrationForm, QuestionForm, AnswerForm, TagForm
from datetime import datetime
from sqlalchemy import and_
from app.mod_user.models import User
from app.mod_answer.models import Answer
from app.mod_question.models import Question
from app.mod_tag.models import Tag
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
#from . import mod_home
mod_home = Blueprint('mod_home', __name__)

@mod_home.route('/')
@mod_home.route('/index')
@mod_home.route('/index/<int:page>', methods=['GET', 'POST'])
def index(page = 1):
	app.config['POSTS_PER_PAGE']
	questions = Question.query.order_by(Question.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
	#questions = Question.query.order_by(Question.timestamp.desc()).paginate(page, POSTS_PER_PAGE, False)
	return render_template('mod_home/index.html', title = 'Welcome', questions = questions)

"""Registers a function to run before each request.The function will be called without any arguments. 
If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	"""filters users by user_id and returns an object of users"""
	def user(user_id):
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

@app.context_processor
def vote_check():
	"""tells number of votes based on whether it is upvote,downvote on question or answer"""
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/mod_tag/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import LoginForm, RegistrationForm, QuestionForm, AnswerForm, TagForm
from app.mod_user.models import User
from app.mod_question.models import Question
from app.mod_answer.models import Answer
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
from app.mod_tag.models import Tag
from datetime import datetime
from sqlalchemy import and_
#from . import mod_tag
mod_tag = Blueprint('mod_tag', __name__)

@mod_tag.route('/searchByTags', methods = ['GET', 'POST'])
def searchByTags():
	"""search question by tags in question database"""
	form = TagForm()
	if form.validate_on_submit():
		tag_data = form.tag.data
		print (tag_data.split(','))
		tags = []
		for tag_body in tag_data.split(','):
			for tag in Tag.query.filter_by(body = tag_body).all():
				tags.append(tag)
		#tags = Tag.query.filter(Tag.body.in_(tag_data)).all()
		questions = []
		for tag in tags:
			question = Question.query.filter_by(question_id = tag.question_id).first()
			if question not in questions:
				questions.append(question)
		return render_template('mod_tag/searchByTags.html', form = form, questions = questions, title = 'Search By Tags')
	return render_template('mod_tag/searchByTags.html',form = form, questions = [], title = 'Search By Tags')

"""@mod_tag.route('/searchByTags', methods = ['GET', 'POST'])
def searchByTags():
	#search question by tags in question database
	form = TagForm()
	if form.validate_on_submit():
		tag_data = form.tag.data
		tags = Tag.query.filter(Tag.body.in_(tag_data)).all()
		questions = []
		for tag in tags:
			question = Question.query.filter_by(question_id = tag.question_id).first()
			if question not in questions:
				questions.append(question)
		return render_template('mod_tag/searchByTags.html', form = form, questions = questions, title = 'Search By Tags')
	return render_template('mod_tag/searchByTags.html',form = form, questions = [], title = 'Search By Tags')"""


"""Registers a function to run before each request.The function will be called without any arguments. 
   If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	def user(user_id):
		"""filters users by user_id and returns an object of users"""
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

"""tells number of votes based on whether it is upvote,downvote on question or answer"""
@app.context_processor
def vote_check():
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/mod_user/__init__.py
#from flask import Blueprint

#mod_user = Blueprint('mod_user', __name__)

#from . import views

src/app/mod_user/views.py
from flask import render_template, flash, redirect, url_for, session, g, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, login_manager
from ..forms import ProfileForm
from .models import User
from app.mod_answer.models import Answer
from app.mod_question.models import Question
from app.mod_tag.models import Tag
from app.mod_vote.models import Upvote, Downvote
from app.mod_comment.models import Comment
from datetime import datetime
from sqlalchemy import and_
#from . import mod_user
mod_user = Blueprint('mod_user', __name__)

@mod_user.route('/user', methods=['GET', 'POST'])
def profile():
	form = ProfileForm()
	if form.validate_on_submit():
		username = form.username.data
		user = User.query.filter_by(username = username).first()
		if user == None:
			flash ('User %s not found' % username)
			return redirect(url_for('mod_user.profile'))
		questions = user.questions.order_by(Question.timestamp.desc())
		return render_template('mod_user/profile.html', title = 'Profile', form = form, questions = questions, user = user)
	else:
		return render_template('mod_user/searchuser.html', title = 'Search User', form = form)

@mod_user.route('/myAnswers')
@mod_user.route('/myAnswers/<int:page>', methods=['GET', 'POST'])
@login_required
def myAnswers(page=1):
	"""This function shows the answers of a particular user"""
	user = User.query.filter_by(user_id = g.user.user_id).first()
	answers = user.answers
	questions = []
	for answer in answers:
		questions.append(answer.question)
	return render_template('mod_user/myAnswers.html', title = 'My Answers', questions = questions)

@mod_user.route('/dashboard')
@mod_user.route('/dashboard/<int:page>', methods=['GET', 'POST'])
@login_required
def dashboard(page=1):
	user = User.query.filter_by(user_id = g.user.user_id).first()
	questions = user.questions.order_by(Question.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
	return render_template('mod_user/dashboard.html', title = 'My Questions', questions = questions)

"""Registers a function to run before each request.The function will be called without any arguments. 
If the function returns a non-None value, it’s handled as if it was the return value from the view and further request handling is stopped"""

@app.before_request
def before_request():
	g.user = current_user
	if g.user.is_authenticated:
		g.user.last_seen = datetime.utcnow()
		db.session.add(g.user)
		db.session.commit()

"""app.context-> Binds the application only. For as long as the application is bound to the current context the flask.current_app points to that application. 
                 An application context is automatically created when a request context is pushed if necessary.
                 """
"""context_processor:Registers a template context processor function."""
@app.context_processor
def utility_processor():
	def user(user_id):
		"""filters users by user_id and returns an object of users"""
		return User.query.filter_by(user_id = user_id).first()
	return dict(user = user)

@app.context_processor
def answer_comments():
	def get_answer_comments(answer_id):
		"""filters answers by anser_id and returns an object of comments filtered"""
		return Comment.query.filter_by(answer_id = answer_id).all()
	return dict(get_answer_comments = get_answer_comments)

@app.context_processor
def answer_id():
	def create_answer_id(answer_id):
		return "add-answer-comment-" + str(answer_id)
	return dict(create_answer_id = create_answer_id)

@app.context_processor
def body_id():
	def create_comment_body_id(answer_id):
		return "comment-body-" + str(answer_id)
	return dict(create_comment_body_id = create_comment_body_id)

@app.context_processor
def vote_check():
	"""tells number of votes based on whether it is upvote,downvote on question or answer"""
	def vote_allowed_check(pid, votetype, contenttype):
		ans = 1
		if g.user.is_authenticated:
			if votetype == 1:
				"""Votetype 1-> Upvote"""
				if contenttype == 1:
					"""Upvote on a question"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Upvote on an answer"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.answer_id == pid)).all())
				else :
					"""Upvote on a comment"""
					ans = len(Upvote.query.filter(and_(Upvote.user_id == g.user.user_id, Upvote.comment_id == pid)).all())
			else : 
				"""Votetype 2->Downvote"""
				if contenttype == 1:
					"""Downvote on a question"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.question_id == pid)).all())
				elif contenttype == 2:
					"""Downvote on an answer"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.answer_id == pid)).all())
				else :
					"""Downvote on a comment"""
					ans = len(Downvote.query.filter(and_(Downvote.user_id == g.user.user_id, Downvote.comment_id == pid)).all())
			print (ans)
		if ans >= 1:
			return 0
		else :
			return 1
	return dict(vote_allowed_check = vote_allowed_check)

src/app/templates/mod_user/dashboard.html
{% extends "base.html" %}
{% block title %} Dashboard {% endblock %}
{% block body %}
<div class="container">
	<div class="container">
		<img src="{{ current_user.avatar(120) }}" style="display: block; margin: auto;">
		<br>
		<h1 style="text-align: center;"><span class="text-warning"> Hello {{ current_user.username }} </span></h1>
    <h4 style="text-align: center;"><span class="text-warning"> You last visited on: <u>
    {{ current_user.last_seen.strftime('%A %d. %B %Y ,%H:%M:%S') }}</u></span></h4>
    <h1 style="text-align: center;"><span class="text-info"> Statistics of {{ current_user.username }} :-</span></h1>
    <table class="table table-striped table-hover table-bordered">
      <br />
       <thead>
    <tr class="success">
      <th style="text-align: center;">#</th>
      <th style="text-align: center;">Activity done by {{ current_user.username }}</th>
      <th style="text-align: center;">Analysis of {{ current_user.username }}</th>
    </tr>
  </thead>
      <tbody>
        <tr class="active">
          <td style="text-align: center;">1</td>
          <td style="text-align: center;">Questions asked</td>
          <td style="text-align: center;">{{ current_user.questions.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">2</td>
          <td style="text-align: center;">Questions answered</td>
          <td style="text-align: center;">{{ current_user.answers.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">3</td>
          <td style="text-align: center;">Upvotes</td>
          <td style="text-align: center;">{{ current_user.upvotes.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">4</td>
          <td style="text-align: center;">Downvotes</td>
          <td style="text-align: center;">{{ current_user.downvotes.all()|length }}</td>
        </tr>
      </tbody>
    </table> 
      </div>
      <br>
      <div class="col-md-12 text-center">
       <ul class="nav nav-pills">
        <li class="active"><a href="{{ url_for('mod_user.dashboard') }}">My Questions</a></li>
        <li><a href="{{ url_for('mod_user.myAnswers') }}">My Answers</a></li>
        <li><a href="{{ url_for('mod_question.addQuestion') }}">Ask A Question</a></li>
      </ul>
    </div>
    <div class="col-md-12 text-center">
      {% for question in questions.items %}
      {% include 'mod_question/questionLink.html' %}
      {% endfor %}
    </div>
    <ul class="pager">
      {% if questions.has_prev %}<li><a href="{{ url_for('mod_user.dashboard', page=questions.prev_num) }}">Previous</a></li>{% else %}<li>Previous</li>{% endif %}  
      {% if questions.has_next %}<li><a href="{{ url_for('mod_user.dashboard', page=questions.next_num) }}">Next</a></li>{% else %}<li>Next</li>{% endif %}
    </ul>    

  </div>
  {% endblock %}

src/app/templates/mod_user/myAnswers.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
<div class="container">
	<div class="container">
		<img src="{{ current_user.avatar(120) }}" style="display: block; margin: auto;">
		<br>
		<p style="text-align: center;"><span class="text-warning"> Welcome {{ current_user.username }} </span></p>
		<p style="text-align: center;"><i> Last seen on: {{ current_user.last_seen }}</i></p>
	</div>
	<br>
	<div class="col-md-12 text-center">
    	<ul class="nav nav-pills">
      		<li><a href="{{ url_for('mod_user.dashboard') }}">My Questions</a></li>
  			<li class="active"><a href="{{ url_for('mod_user.myAnswers') }}">My Answers</a></li>
  			<li><a href="{{ url_for('mod_question.addQuestion') }}">Ask A Question</a></li>
    	</ul>
	</div>
	<div class="col-md-12 text-center">
        {% for question in questions %}
            {% include 'mod_question/questionLink.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

src/app/templates/mod_user/profile.html
{% extends "base.html" %}
{% block title %} Dashboard {% endblock %}
{% block body %}
<div class="container">
	<div class="container">
		<img src="{{ user.avatar(120) }}" style="display: block; margin: auto;">
		<br>
    <h1 style="text-align: center;"><span class="text-info"> Statistics of {{ user.username }} </span></h1>
    <table class="table table-striped table-hover table-bordered">
      <br />
       <thead>
    <tr class="success">
      <th style="text-align: center;">#</th>
      <th style="text-align: center;">Activity done by {{ user.username }}</th>
      <th style="text-align: center;">Analysis of {{ user.username }}</th>
    </tr>
  </thead>
      <tbody>
        <tr class="active">
          <td style="text-align: center;">1</td>
          <td style="text-align: center;">Questions asked</td>
          <td style="text-align: center;">{{ user.questions.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">2</td>
          <td style="text-align: center;">Questions answered</td>
          <td style="text-align: center;">{{ user.answers.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">3</td>
          <td style="text-align: center;">Upvotes</td>
          <td style="text-align: center;">{{ user.upvotes.all()|length }}</td>
        </tr>
        <tr class="active">
          <td style="text-align: center;">4</td>
          <td style="text-align: center;">Downvotes</td>
          <td style="text-align: center;">{{ user.downvotes.all()|length }}</td>
        </tr>
      </tbody>
    </table> 
      </div>
      <br>
      <div class="col-md-12 text-center">
    <h2 style="text-align: center;"><span class="text-info"> Questions Asked</span></h2>
    <div class="col-md-12 text-center">
      {% for question in questions %}
      {% include 'mod_question/questionLink.html' %}
      {% endfor %}
    </div>
  </div>
  {% endblock %}

src/app/templates/mod_user/searchuser.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %} Search User {% endblock %}
{% block body %}

<div class="container">
	<div class="col-md-12 text-center">
        <ul class="nav nav-pills">
            <li><a href="{{ url_for('mod_home.index') }}">All</a></li>
            <li><a href="{{ url_for('mod_question.unansweredQuestions') }}">Unanswered</a></li>
            <li><a href="{{ url_for('mod_question.answeredQuestions') }}">Answered</a></li>
            <li><a href="{{ url_for('mod_tag.searchByTags') }}">Search By Tags</a></li>
            <li class="active"><a href="{{ url_for('mod_user.profile') }}">Search User</a></li>
        </ul>
    </div>
    <br>
    <br>	
	<div class="content-section">
		<br>
		{{ utils.flashed_messages() }}
		</br>
		<div class="center">
			<h1 style="text-align: center;">Search User</h1>
			<form class="form" method="POST" action="" role="form">
				{{form.csrf_token}}
				{{wtf.form_field(form.username)}}
    			<br>					
				{{wtf.form_field(form.submit)}}
			</form>
		</div>
	</div>
</div>
{% endblock %}